backend:
  name: github
  branch: master
  repo: Logicbuilds/compassglass

media_folder: public/content/media
public_folder: /content/media
show_preview_links: false

slug:
  encoding: 'ascii'
  clean_accents: true
sanitize_replacement: '_'

collections:
  - name: settings
    label: Settings
    editor:
      preview: false
    delete: false
    files:
      - file: public/manifest.json
        name: manifest
        label: Manifest Settings
        fields:
          - {
              name: short_name,
              label: Short Name,
              widget: string,
              required: true,
            }
          - { name: name, label: Name, widget: string, required: true }
          - {
              name: start_url,
              label: 'Start URL',
              widget: string,
              default: 'https://compassglass.co.za/',
              required: true,
            }
          - {
              name: url,
              label: 'URL',
              widget: string,
              default: 'https://compassglass.co.za/',
              required: true,
            }
          - {
              name: lang,
              label: 'Language',
              widget: string,
              default: 'en',
              required: true,
            }
          - {
              name: display,
              label: 'Display Type',
              widget: string,
              default: 'standalone',
              required: true,
            }
          - {
              name: theme_color,
              label: 'Theme Color',
              widget: string,
              default: '#000000',
              required: true,
            }
          - {
              name: background_color,
              label: 'Background Color',
              widget: string,
              default: '#FFFFFF',
              required: true,
            }
          - {
              name: orientation,
              label: 'Orientation',
              widget: string,
              default: 'portrait',
              required: true,
            }
          - name: icons
            label: Icons
            widget: list
            allow_add: true
            fields:
              - { name: src, label: Source, widget: string }
              - { name: sizes, label: Sizes, widget: string }
              - { name: type, label: 'Mime Type', widget: string }
          - name: screenshots
            label: Screenshots
            widget: list
            allow_add: true
            default: []
            fields:
              - { name: src, label: Source, widget: string }
              - { name: sizes, label: Sizes, widget: string }
              - { name: type, label: 'Mime Type', widget: string }
  - name: pages
    label: Pages
    delete: false
    editor:
      preview: false
    files:
      - file: public/content/pages/home.json
        name: home
        label: Home
        fields:
          - name: content
            label: Content
            widget: list
            fields:
              - { name: title, label: Title, widget: string, required: true }
              - { name: body, label: Body, widget: markdown, required: true }
      - file: public/content/pages/about.json
        name: about
        label: About
        fields:
          - { name: title, label: Title, widget: string, required: true }
          - { name: content, label: Content, widget: string, required: true }
      - file: public/content/pages/faqs.json
        name: faqs
        label: FAQ's
        fields:
          - { name: title, label: Title, widget: string, required: true }
          - name: content
            label: Content
            widget: list
            fields:
              - {
                  name: question,
                  label: Question,
                  widget: string,
                  required: true,
                }
              - {
                  name: answer,
                  label: Answer,
                  widget: markdown,
                  required: true,
                }
      - file: public/content/pages/technical.json
        name: technical
        label: Technical
        fields:
          - { name: title, label: Title, widget: string, required: true }
          - name: whatIsGlass
            label: What is glass
            widget: object
            fields:
              - { name: title, label: Title, widget: string, required: true }
              - {
                  name: content,
                  label: Content,
                  widget: markdown,
                  required: true,
                }
          - name: compositionOfCommercialGlass
            label: Composition of commercial glass
            widget: object
            fields:
              - { name: title, label: Title, widget: string, required: true }
              - {
                  name: subTitle,
                  label: Sub title,
                  widget: string,
                  required: true,
                }
              - name: content
                label: Content
                widget: list
                fields:
                  - {
                      name: origin,
                      label: Origin,
                      widget: string,
                      required: true,
                    }
                  - name: data
                    label: Data
                    widget: list
                    fields:
                      - name: description
                        label: Description
                        widget: object
                        equired: true
                        fields:
                          - {
                              name: value1,
                              label: Column 1 Value,
                              widget: string,
                              required: true,
                            }
                          - {
                              name: value2,
                              label: Column 2 Value,
                              widget: string,
                              required: true,
                            }
                      - {
                          name: percentage,
                          label: Percentage,
                          widget: string,
                          required: true,
                        }
                    allow_add: true
                    required: true
                required: true
            required: true
          - {
              name: disclaimer,
              label: Disclaimer,
              widget: markdown,
              required: true,
            }
      - file: public/content/pages/contact.json
        name: contact
        label: Contact
        fields:
          - name: content
            label: Content
            widget: list
            fields:
              - { name: title, label: Title, widget: string, required: true }
              - {
                  name: address,
                  label: Address,
                  widget: string,
                  required: true,
                }
              - { name: phone, label: Phone, widget: string, required: true }
              - { name: email, label: Email, widget: string, required: true }
              - {
                  name: directions,
                  label: Directions,
                  widget: string,
                  required: true,
                }
